[env.collectors.datadog-checks]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[[envs.default.matrix]]
python = ["27", "38"]
version = ["13.12.0", "14.1.0"]

[envs.default.overrides]
matrix.version.env-vars = "GITLAB_RUNNER_VERSION"

[envs.bench]