[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["27", "38"]
version = ["v4.0.21-stable-4.0-nautilus-centos-7", "v5.0.7-stable-5.0-octopus-centos-8"]

[envs.default.overrides]
matrix.version.env-vars = "CEPH_VERSION"
